spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banco_api_test?useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop  ## Cria e apaga o schema a cada execução dos testes
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
