spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banco_api?useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: $(DB_PASSWORD)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
