spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banco_api?useSSL=false&serverTimezone=UTC
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
